title: Site

tabs:
  content:
    columns:
      - width: 1/2
        fields:
          announcement:
            type: textarea
            label: Announcement
          phonetimes:
            type: structure
            label: Telefontider
            fields:
              day:
                type: date
                width: 1/4
              from:
                type: number
                default: 10
                width: 1/4
              to:
                type: number
                default: 12
                width: 1/4
              toggle:
                type: toggle
                label: Sold out?
                width: 1/4
          quotes:
            type: structure
            label: Quotes
            fields:
              text:
                type: text
                default: '"Citat" — Kunstner, Titel(eller årstal)'
          testimonials:
            type: structure
            label: Testimonials
            fields:
              quote:
                label: Quote
                type: text
              author:
                label: Who's it from?
                type: textarea
          eventphoto:
            label: Photo for Talks section
            type: files
            multiple: false
          guest:
            label: Guest name
            type: text
            size: small
          eventdescription:
            label: Short description
            type: textarea
          eventdate:
            label: Date
            type: date
          toggle:
            label: Podcast or ticket link?
            type: toggle
            text:
              - Podcast
              - Ticket
          eventlink:
            label: Podcast/ticket url
            type: url
      - width: 1/2
        sections:
          pages:
            type: pages
            sortable: false
            delete: false
          team: sections/team

